### ISSUE TITLE
[BLUEMARLIN-31] : For DIN-Lookalike model in TF2.0, it is being trained using pickle file.

### ISSUE THREAD

**Issue by Bimlesh759-AI** [Futurewei-io/blue-marlin#270]
1. Training of model in TF2 code is happening with pickle file but it should be trained using  tfrecord?

**Comment by jimmylao** [comment]
@Bimlesh759-AI 
lets have a discussion about it at 9am EST (3/30)
https://futurewei.zoom.us/j/6930705942

**Comment by Bimlesh759-AI** [comment]
When can we get updated trainer code for tf2.0 where training is done using tfrecord instead of pickle file

**Comment by jimmylao** [comment]
@Bimlesh759-AI Will update tomorrow or Wednesday.

**Comment by Bimlesh759-AI** [comment]
Two issues are coming in new trainer code-> Need discussion on these two issue.
1. While parsing datasets, following are the error shown:
Traceback (most recent call last):
  File "schedule-train/algorithm/lookalike_model/trainer/train_tf2_tfrecord.py", line 88, in <module>
    for next_element_test in batched_dataset_test:
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 622, in __next__
    return self.next()
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 666, in next
    return self._next_internal()
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2691, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_<lambda>_368}} Key: keyword_list_padded.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]] [Op:IteratorGetNextSync]

2. This issue will come while validating the model, Currently all the test data are stored in list, in our cases we have millions of data in test_tfrecord, so it wont be ideally possible to store in list. This part should also be handled with batch wise input of datasets like what is currently done for training part.

**Comment by Bimlesh759-AI** [comment]
Update on new tf2 trainer code:

1. Training is failing after first iteration of batch with following errors. This error may be happening due to batch size mismatch. After first batch of training, error comes.

***********************compute batch 0 batch size 40960***********************
Train on 40960 samples, validate on 10240 samples
/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

40960/40960 [==============================] - 2s 50us/sample
Traceback (most recent call last):
  File "/opt/schedule-train/algorithm/lookalike_model/trainer/train_tf2_MTP.py", line 132, in <module>
    batch_size=batch_size_here,
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 727, in fit
    use_multiprocessing=use_multiprocessing)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 331, in fit
    total_epochs=epochs)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 461, in __call__
    return self._stateless_fn(*args, **kwds)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1822, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[16362,7] = 16 is not in [0, 16)
	 [[node din/embedding/embedding_lookup (defined at root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Invalid argument:  indices[16362,7] = 16 is not in [0, 16)
	 [[node din/embedding/embedding_lookup (defined at root/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[metrics/auc/assert_less_equal/Assert/AssertGuard/else/_11/Assert/data_0/_58]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_3758]

Function call stack:
distributed_function -> distributed_function

**Comment by jimmylao** [comment]
It looks like you made some changes to the code and running in multiprocessing mode. Can you post the code you are running, especially those changes that are different from trainer2_tfrecord.py posted on Github?

**Comment by Bimlesh759-AI** [comment]
Code is running fine on single GPU currently.

Our goal is to run this code on multiple gpu, Currently this is not optimized for multiple gpu ? 4 gpus are available but only one is used.
Can we run this code on multiple GPUs.

**Comment by Bimlesh759-AI** [comment]
Hi @jimmylao , Can you commit trainer code for multiple gpu? We can also test multiple gpu trainer code in our environment. Current trainer code runs only on single GPU.

**Comment by jimmylao** [comment]
@Bimlesh759-AI Please find performance comparison test in the attached pdf file. Based on the document, multiGPU trainer does not generate expected speedup. 
Please let me know if you still want the multiGPU trainer code.
[multi-gpu-summary-tf2.pdf](https://github.com/Futurewei-io/blue-marlin/files/8532141/multi-gpu-summary-tf2.pdf)
.
